import { BackgroundLibraryAsset } from "@/lib/types";

export const builtInBackgroundAssets: BackgroundLibraryAsset[] = [
  {
    id: "builtin-aurora-retail",
    label: "Aurora Retail",
    category: "Retail",
    imageUrl: "/backgrounds/aurora-retail.svg",
    thumbnailUrl: "/backgrounds/aurora-retail.svg",
    source: "built-in",
  },
  {
    id: "builtin-sunset-dining",
    label: "Sunset Dining",
    category: "Food",
    imageUrl: "/backgrounds/sunset-dining.svg",
    thumbnailUrl: "/backgrounds/sunset-dining.svg",
    source: "built-in",
  },
  {
    id: "builtin-midnight-neon",
    label: "Midnight Neon",
    category: "Gaming",
    imageUrl: "/backgrounds/midnight-neon.svg",
    thumbnailUrl: "/backgrounds/midnight-neon.svg",
    source: "built-in",
  },
  {
    id: "builtin-soft-studio",
    label: "Soft Studio",
    category: "Beauty",
    imageUrl: "/backgrounds/soft-studio.svg",
    thumbnailUrl: "/backgrounds/soft-studio.svg",
    source: "built-in",
  },
  {
    id: "builtin-scratch-beauty-nude-elegance",
    label: "Nude Élégance — ticket à gratter",
    category: "Beauté & bien-être",
    imageUrl: "/images/scratch-templates/beauty-nude-elegance.webp",
    thumbnailUrl: "/images/scratch-templates/beauty-nude-elegance.webp",
    source: "built-in",
    width: 900,
    height: 1350,
  },
  {
    id: "builtin-scratch-beauty-botanical-premium",
    label: "Botanique Premium — ticket à gratter",
    category: "Beauté & bien-être",
    imageUrl: "/images/scratch-templates/beauty-botanical-premium.webp",
    thumbnailUrl: "/images/scratch-templates/beauty-botanical-premium.webp",
    source: "built-in",
    width: 900,
    height: 1350,
  },
  {
    id: "builtin-scratch-beauty-noir-or",
    label: "Noir & Or Signature — ticket à gratter",
    category: "Beauté & bien-être",
    imageUrl: "/images/scratch-templates/beauty-noir-or.webp",
    thumbnailUrl: "/images/scratch-templates/beauty-noir-or.webp",
    source: "built-in",
    width: 900,
    height: 1350,
  },
  {
    id: "builtin-scratch-beauty-lilas",
    label: "Lilas Soin Doux — ticket à gratter",
    category: "Beauté & bien-être",
    imageUrl: "/images/scratch-templates/beauty-lilas-soin-doux.webp",
    thumbnailUrl: "/images/scratch-templates/beauty-lilas-soin-doux.webp",
    source: "built-in",
    width: 900,
    height: 1350,
  },
  {
    id: "builtin-scratch-beauty-corail",
    label: "Corail Lumière — ticket à gratter",
    category: "Beauté & bien-être",
    imageUrl: "/images/scratch-templates/beauty-corail-lumiere.webp",
    thumbnailUrl: "/images/scratch-templates/beauty-corail-lumiere.webp",
    source: "built-in",
    width: 900,
    height: 1350,
  },
  {
    id: "builtin-scratch-classic-nude",
    label: "Nude — fond neutre",
    category: "Beauté & bien-être",
    imageUrl: "/images/scratch-templates/nude-neutral-background.webp",
    thumbnailUrl: "/images/scratch-templates/nude-neutral-background.webp",
    source: "built-in",
    width: 1024,
    height: 1536,
  },
  {
    id: "builtin-terracotta-bistro",
    label: "Terracotta Bistro",
    category: "Restauration",
    imageUrl: "/backgrounds/terracotta-bistro.svg",
    thumbnailUrl: "/backgrounds/terracotta-bistro.svg",
    source: "built-in",
    width: 1024,
    height: 1536,
  },
  {
    id: "builtin-lemon-market",
    label: "Lemon Market",
    category: "Commerce",
    imageUrl: "/backgrounds/lemon-market.svg",
    thumbnailUrl: "/backgrounds/lemon-market.svg",
    source: "built-in",
    width: 1024,
    height: 1536,
  },
  {
    id: "builtin-coral-ritual",
    label: "Coral Ritual",
    category: "Beauté & bien-être",
    imageUrl: "/backgrounds/coral-ritual.svg",
    thumbnailUrl: "/backgrounds/coral-ritual.svg",
    source: "built-in",
    width: 1024,
    height: 1536,
  },
  {
    id: "builtin-cobalt-celebration",
    label: "Cobalt Celebration",
    category: "Événementiel",
    imageUrl: "/backgrounds/cobalt-celebration.svg",
    thumbnailUrl: "/backgrounds/cobalt-celebration.svg",
    source: "built-in",
    width: 1024,
    height: 1536,
  },
  {
    id: "builtin-mint-botanica",
    label: "Mint Botanica",
    category: "Commerce",
    imageUrl: "/backgrounds/mint-botanica.svg",
    thumbnailUrl: "/backgrounds/mint-botanica.svg",
    source: "built-in",
    width: 1024,
    height: 1536,
  },
  {
    id: "builtin-lavender-atelier",
    label: "Lavender Atelier",
    category: "Beauté & bien-être",
    imageUrl: "/backgrounds/lavender-atelier.svg",
    thumbnailUrl: "/backgrounds/lavender-atelier.svg",
    source: "built-in",
    width: 1024,
    height: 1536,
  },
  {
    id: "builtin-sandy-escape",
    label: "Sandy Escape",
    category: "Loisirs",
    imageUrl: "/backgrounds/sandy-escape.svg",
    thumbnailUrl: "/backgrounds/sandy-escape.svg",
    source: "built-in",
    width: 1024,
    height: 1536,
  },
  {
    id: "builtin-fuchsia-play",
    label: "Fuchsia Play",
    category: "Loisirs",
    imageUrl: "/backgrounds/fuchsia-play.svg",
    thumbnailUrl: "/backgrounds/fuchsia-play.svg",
    source: "built-in",
    width: 1024,
    height: 1536,
  },
];
