import { BackgroundLibraryAsset } from "@/lib/types";

export const builtInBackgroundAssets: BackgroundLibraryAsset[] = [
  {
    id: "builtin-aurora-retail",
    label: "Aurora Retail",
    category: "Retail",
    imageUrl: "/backgrounds/aurora-retail.svg",
    thumbnailUrl: "/backgrounds/aurora-retail.svg",
    source: "built-in",
  },
  {
    id: "builtin-sunset-dining",
    label: "Sunset Dining",
    category: "Food",
    imageUrl: "/backgrounds/sunset-dining.svg",
    thumbnailUrl: "/backgrounds/sunset-dining.svg",
    source: "built-in",
  },
  {
    id: "builtin-midnight-neon",
    label: "Midnight Neon",
    category: "Gaming",
    imageUrl: "/backgrounds/midnight-neon.svg",
    thumbnailUrl: "/backgrounds/midnight-neon.svg",
    source: "built-in",
  },
  {
    id: "builtin-soft-studio",
    label: "Soft Studio",
    category: "Beauty",
    imageUrl: "/backgrounds/soft-studio.svg",
    thumbnailUrl: "/backgrounds/soft-studio.svg",
    source: "built-in",
  },
  {
    id: "builtin-terracotta-bistro",
    label: "Terracotta Bistro",
    category: "Restauration",
    imageUrl: "/backgrounds/terracotta-bistro.svg",
    thumbnailUrl: "/backgrounds/terracotta-bistro.svg",
    source: "built-in",
    width: 1024,
    height: 1536,
  },
  {
    id: "builtin-lemon-market",
    label: "Lemon Market",
    category: "Commerce",
    imageUrl: "/backgrounds/lemon-market.svg",
    thumbnailUrl: "/backgrounds/lemon-market.svg",
    source: "built-in",
    width: 1024,
    height: 1536,
  },
  {
    id: "builtin-coral-ritual",
    label: "Coral Ritual",
    category: "Beauté & bien-être",
    imageUrl: "/backgrounds/coral-ritual.svg",
    thumbnailUrl: "/backgrounds/coral-ritual.svg",
    source: "built-in",
    width: 1024,
    height: 1536,
  },
  {
    id: "builtin-cobalt-celebration",
    label: "Cobalt Celebration",
    category: "Événementiel",
    imageUrl: "/backgrounds/cobalt-celebration.svg",
    thumbnailUrl: "/backgrounds/cobalt-celebration.svg",
    source: "built-in",
    width: 1024,
    height: 1536,
  },
  {
    id: "builtin-mint-botanica",
    label: "Mint Botanica",
    category: "Commerce",
    imageUrl: "/backgrounds/mint-botanica.svg",
    thumbnailUrl: "/backgrounds/mint-botanica.svg",
    source: "built-in",
    width: 1024,
    height: 1536,
  },
  {
    id: "builtin-lavender-atelier",
    label: "Lavender Atelier",
    category: "Beauté & bien-être",
    imageUrl: "/backgrounds/lavender-atelier.svg",
    thumbnailUrl: "/backgrounds/lavender-atelier.svg",
    source: "built-in",
    width: 1024,
    height: 1536,
  },
  {
    id: "builtin-sandy-escape",
    label: "Sandy Escape",
    category: "Loisirs",
    imageUrl: "/backgrounds/sandy-escape.svg",
    thumbnailUrl: "/backgrounds/sandy-escape.svg",
    source: "built-in",
    width: 1024,
    height: 1536,
  },
  {
    id: "builtin-fuchsia-play",
    label: "Fuchsia Play",
    category: "Loisirs",
    imageUrl: "/backgrounds/fuchsia-play.svg",
    thumbnailUrl: "/backgrounds/fuchsia-play.svg",
    source: "built-in",
    width: 1024,
    height: 1536,
  },
];
